import {
  Customer,
  Payment,
  Subscription,
  Invoice,
  RecoveryCase,
  RevenueRisk,
  AgentDecision,
  AuditEvent,
} from "../../types";

export interface SeedData {
  customers: Customer[];
  payments: Payment[];
  subscriptions: Subscription[];
  invoices: Invoice[];
  recoveryCases: RecoveryCase[];
  revenueRisks: RevenueRisk[];
  agentDecisions: AgentDecision[];
  auditEvents: AuditEvent[];
}

export function getInitialSeedData(): SeedData {
  const now = new Date();
  const isoNow = now.toISOString();
  const oneHourAgo = new Date(now.getTime() - 3600 * 1000).toISOString();
  const twoHoursAgo = new Date(now.getTime() - 2 * 3600 * 1000).toISOString();
  const fourHoursAgo = new Date(now.getTime() - 4 * 3600 * 1000).toISOString();
  const oneDayAgo = new Date(now.getTime() - 24 * 3600 * 1000).toISOString();
  const twoDaysAgo = new Date(now.getTime() - 48 * 3600 * 1000).toISOString();
  const threeDaysAgo = new Date(now.getTime() - 72 * 3600 * 1000).toISOString();

  // 1. Customers
  const customers: Customer[] = [
    {
      id: "cust_zenith_01",
      name: "Aakash Verma",
      email: "finance@zenithedutech.in",
      phone: "+919876543210",
      companyName: "Zenith Edutech Pvt Ltd",
      gstNumber: "29AABCZ1234F1Z8",
      tier: "ENTERPRISE",
      ltv: 450000,
      preferredPaymentMethod: "nach",
      failureCount: 1,
      recoveryCount: 2,
      activeSubscriptionId: "sub_zenith_annual_01",
      createdAt: "2025-01-10T10:00:00Z",
      updatedAt: isoNow,
    },
    {
      id: "cust_hyperlocal_02",
      name: "Pooja Deshmukh",
      email: "billing@hyperlocaldelivery.co",
      phone: "+919811223344",
      companyName: "HyperLocal Logistics India",
      gstNumber: "27AABCH9876G1ZQ",
      tier: "GROWTH",
      ltv: 180000,
      preferredPaymentMethod: "card",
      failureCount: 2,
      recoveryCount: 1,
      activeSubscriptionId: "sub_hyperlocal_monthly_02",
      createdAt: "2025-03-15T11:30:00Z",
      updatedAt: isoNow,
    },
    {
      id: "cust_chaicrafters_03",
      name: "Rohit Sharma",
      email: "rohit@chaicrafters.in",
      phone: "+919123456789",
      companyName: "ChaiCrafters Gourmet",
      gstNumber: "07AAACC5555L1Z1",
      tier: "D2C",
      ltv: 35000,
      preferredPaymentMethod: "upi",
      failureCount: 1,
      recoveryCount: 0,
      activeSubscriptionId: "sub_chaicrafters_monthly_03",
      createdAt: "2025-06-20T09:15:00Z",
      updatedAt: isoNow,
    },
    {
      id: "cust_logitrack_04",
      name: "Suresh Menon",
      email: "suresh.menon@logitrack.io",
      phone: "+919744112233",
      companyName: "LogiTrack Systems India",
      gstNumber: "33AABBL4321E1Z4",
      tier: "ENTERPRISE",
      ltv: 620000,
      preferredPaymentMethod: "card",
      failureCount: 1,
      recoveryCount: 3,
      activeSubscriptionId: "sub_logitrack_quarterly_04",
      createdAt: "2024-11-05T14:20:00Z",
      updatedAt: isoNow,
    },
    {
      id: "cust_finstack_05",
      name: "Ananya Iyer",
      email: "ananya@finstack.tech",
      phone: "+919888776611",
      companyName: "FinStack Analytics",
      gstNumber: "29AABCF8888D1Z2",
      tier: "ENTERPRISE",
      ltv: 540000,
      preferredPaymentMethod: "netbanking",
      failureCount: 1,
      recoveryCount: 1,
      activeSubscriptionId: "sub_finstack_monthly_05",
      createdAt: "2025-02-18T16:45:00Z",
      updatedAt: isoNow,
    },
    {
      id: "cust_cloudnest_07",
      name: "Vikram Malhotra",
      email: "vikram@cloudnest.co.in",
      phone: "+919900112233",
      companyName: "CloudNest Infrastructure Labs",
      gstNumber: "06AABCC9999K1Z3",
      tier: "ENTERPRISE",
      ltv: 960000,
      preferredPaymentMethod: "nach",
      failureCount: 0,
      recoveryCount: 4,
      activeSubscriptionId: "sub_cloudnest_annual_07",
      createdAt: "2024-08-10T12:00:00Z",
      updatedAt: isoNow,
    },
  ];

  // 2. Payments
  const payments: Payment[] = [
    {
      id: "pay_zenith_001",
      razorpayPaymentId: "pay_rzp_zenith_9812",
      customerId: "cust_zenith_01",
      amount: 149999,
      currency: "INR",
      status: "failed",
      method: "nach",
      bank: "HDFC Bank",
      errorCode: "INSUFFICIENT_FUNDS",
      errorDescription: "NACH mandate presentation rejected due to balance limit during early clearing cycle",
      errorSource: "bank",
      errorReason: "insufficient_funds",
      errorStep: "mandate_execution",
      attempts: 1,
      lastAttemptAt: fourHoursAgo,
      createdAt: fourHoursAgo,
    },
    {
      id: "pay_hyperlocal_002",
      razorpayPaymentId: "pay_rzp_hyperlocal_3421",
      customerId: "cust_hyperlocal_02",
      amount: 24999,
      currency: "INR",
      status: "failed",
      method: "card",
      cardNetwork: "VISA",
      cardLast4: "4242",
      bank: "ICICI Bank",
      errorCode: "PAYMENT_AUTHENTICATION_FAILED",
      errorDescription: "Customer 3DS 2.0 authentication dropped out on OTP challenge screen",
      errorSource: "customer",
      errorReason: "otp_timeout",
      errorStep: "payment_authentication",
      attempts: 2,
      lastAttemptAt: twoHoursAgo,
      createdAt: twoHoursAgo,
    },
    {
      id: "pay_chaicrafters_003",
      razorpayPaymentId: "pay_rzp_chai_7761",
      customerId: "cust_chaicrafters_03",
      amount: 2499,
      currency: "INR",
      status: "failed",
      method: "upi",
      vpa: "rohit.sharma@okaxis",
      bank: "AXIS Bank",
      errorCode: "UPI_COLLECT_TIMEOUT",
      errorDescription: "UPI collect intent notification expired without customer approval",
      errorSource: "gateway",
      errorReason: "collect_timeout",
      errorStep: "payment_authorization",
      attempts: 1,
      lastAttemptAt: oneHourAgo,
      createdAt: oneHourAgo,
    },
    {
      id: "pay_logitrack_004",
      razorpayPaymentId: "pay_rzp_logi_5512",
      customerId: "cust_logitrack_04",
      amount: 79000,
      currency: "INR",
      status: "failed",
      method: "card",
      cardNetwork: "MASTERCARD",
      cardLast4: "8890",
      bank: "State Bank of India",
      errorCode: "CARD_EXPIRED",
      errorDescription: "Card expiry date (07/26) expired. Recurring token invalidated.",
      errorSource: "bank",
      errorReason: "card_expired",
      errorStep: "payment_authorization",
      attempts: 1,
      lastAttemptAt: oneDayAgo,
      createdAt: oneDayAgo,
    },
    {
      id: "pay_cloudnest_007",
      razorpayPaymentId: "pay_rzp_cloud_9981",
      customerId: "cust_cloudnest_07",
      amount: 320000,
      currency: "INR",
      status: "captured",
      method: "upi",
      vpa: "vikram.m@oksbi",
      bank: "State Bank of India",
      attempts: 2,
      lastAttemptAt: twoDaysAgo,
      createdAt: threeDaysAgo,
    },
  ];

  // 3. Subscriptions
  const subscriptions: Subscription[] = [
    {
      id: "sub_zenith_annual_01",
      razorpaySubscriptionId: "sub_rzp_zenith_001",
      customerId: "cust_zenith_01",
      planName: "Enterprise LMS Annual",
      planCode: "PLAN_ENT_LMS_YR",
      amount: 149999,
      currency: "INR",
      status: "active",
      billingInterval: "annual",
      currentPeriodStart: "2025-08-20T00:00:00Z",
      currentPeriodEnd: "2026-08-20T00:00:00Z",
      nextBillingAt: isoNow,
      failureCount: 1,
      retryStrategy: "AI_ADAPTIVE",
      mandateId: "mandate_hdfc_zenith_88",
      mandateStatus: "active",
      createdAt: "2025-08-20T00:00:00Z",
      updatedAt: isoNow,
    },
    {
      id: "sub_hyperlocal_monthly_02",
      razorpaySubscriptionId: "sub_rzp_hyper_002",
      customerId: "cust_hyperlocal_02",
      planName: "Growth Dispatch Engine",
      planCode: "PLAN_GROWTH_MTH",
      amount: 24999,
      currency: "INR",
      status: "active",
      billingInterval: "monthly",
      currentPeriodStart: "2026-07-27T00:00:00Z",
      currentPeriodEnd: "2026-08-27T00:00:00Z",
      nextBillingAt: isoNow,
      failureCount: 2,
      retryStrategy: "AI_ADAPTIVE",
      mandateId: "mandate_icici_hyper_44",
      mandateStatus: "active",
      createdAt: "2026-03-27T00:00:00Z",
      updatedAt: isoNow,
    },
  ];

  // 4. Invoices
  const invoices: Invoice[] = [
    {
      id: "inv_zenith_101",
      invoiceNumber: "INV-2026-08-101",
      razorpayInvoiceId: "inv_rzp_zenith_101",
      customerId: "cust_zenith_01",
      subscriptionId: "sub_zenith_annual_01",
      paymentId: "pay_zenith_001",
      subtotal: 127118,
      taxAmount: 22881, // 18% GST
      totalAmount: 149999,
      currency: "INR",
      status: "past_due",
      issuedDate: fourHoursAgo,
      dueDate: isoNow,
      lineItems: [
        {
          id: "item_1",
          description: "Enterprise LMS Annual License (500 seats)",
          quantity: 1,
          unitPrice: 127118,
          amount: 127118,
          taxRate: 18,
          taxAmount: 22881,
        },
      ],
      createdAt: fourHoursAgo,
    },
  ];

  // 5. Recovery Cases
  const recoveryCases: RecoveryCase[] = [
    {
      id: "case_rec_001",
      caseNumber: "REC-2026-0891",
      customerId: "cust_zenith_01",
      paymentId: "pay_zenith_001",
      subscriptionId: "sub_zenith_annual_01",
      invoiceId: "inv_zenith_101",
      razorpayPaymentId: "pay_rzp_zenith_9812",
      amount: 149999,
      currency: "INR",
      status: "IN_PROGRESS",
      riskLevel: "CRITICAL",
      riskScore: 82,
      recoverabilityScore: 92,
      expectedRecoveryValue: 137999,
      priority: "P0",
      rootCause: "INSUFFICIENT_FUNDS",
      rootCauseDetails: "HDFC CBS declined early-morning NACH presentation. Indian corporate salary/disbursement cycle occurs between 1st-3rd of month.",
      selectedAction: "RETRY_SUBSCRIPTION",
      currentStep: "SMART_RETRY_SCHEDULED",
      actionsTakenCount: 2,
      recoveryAttempts: 1,
      recoveredAmount: 0,
      totalRecoveredAmount: 0,
      requiresHumanApproval: true,
      paymentLinkUrl: "https://rzp.io/i/demo_rec_zenith_01",
      scheduledRetries: [
        {
          id: "ret_001",
          scheduledAt: new Date(now.getTime() + 6 * 3600 * 1000).toISOString(),
          channel: "AUTO_RETRY",
          status: "PENDING",
          resultNote: "Scheduled for 02:45 PM during peak interbank clearing liquidity window",
        },
      ],
      aiRecommendation: {
        action: "Schedule Smart Mandate Retry for afternoon clearing window + Dispatch WhatsApp reminder with zero-friction Razorpay UPI Intent button.",
        actionType: "SMART_SCHEDULED_RETRY",
        confidence: 0.94,
        reasoning: "Enterprise client with high historical LTV (₹4.5L). Past 2 renewals succeeded when presented between 2:00 PM and 4:00 PM IST.",
        optimalRetryTime: "Today at 02:45 PM IST",
        recommendedChannel: "WHATSAPP",
        expectedRecoveryProbability: 0.92,
      },
      customer: customers[0],
      payment: payments[0],
      subscription: subscriptions[0],
      timeline: [
        {
          id: "tl_001",
          timestamp: fourHoursAgo,
          title: "Razorpay Mandate Payment Failed",
          description: "₹1,49,999 debit failed via HDFC NACH mandate due to INSUFFICIENT_FUNDS error code.",
          type: "PAYMENT_FAILED",
          actor: "RAZORPAY_WEBHOOK",
        },
        {
          id: "tl_002",
          timestamp: fourHoursAgo,
          title: "RecoverAI Autonomous Case Generated",
          description: "Assigned CRITICAL risk level. Root cause classified as clearing-hour balance drop.",
          type: "AGENT_ANALYSIS",
          actor: "RECOVER_AI_AGENT",
        },
        {
          id: "tl_003",
          timestamp: threeDaysAgo,
          title: "Smart Retry Queued & Interactive WhatsApp Dispatched",
          description: "Generated dynamic Razorpay payment link and scheduled auto-retry for 02:45 PM window.",
          type: "ACTION_EXECUTED",
          actor: "RECOVER_AI_AGENT",
        },
      ],
      createdAt: fourHoursAgo,
      updatedAt: isoNow,
    },
    {
      id: "case_rec_002",
      caseNumber: "REC-2026-0892",
      customerId: "cust_hyperlocal_02",
      paymentId: "pay_hyperlocal_002",
      subscriptionId: "sub_hyperlocal_monthly_02",
      razorpayPaymentId: "pay_rzp_hyperlocal_3421",
      amount: 24999,
      currency: "INR",
      status: "IN_PROGRESS",
      riskLevel: "HIGH",
      riskScore: 74,
      recoverabilityScore: 86,
      expectedRecoveryValue: 21499,
      priority: "P1",
      rootCause: "AUTHENTICATION_DROPOFF",
      rootCauseDetails: "Customer abandoned 3DS OTP validation screen. Card is valid and has ample limit.",
      selectedAction: "CREATE_PAYMENT_LINK",
      currentStep: "INTERACTIVE_WHATSAPP_SENT",
      actionsTakenCount: 1,
      recoveryAttempts: 1,
      recoveredAmount: 0,
      totalRecoveredAmount: 0,
      requiresHumanApproval: false,
      paymentLinkUrl: "https://rzp.io/i/demo_rec_hyperlocal_02",
      scheduledRetries: [
        {
          id: "ret_002",
          scheduledAt: new Date(now.getTime() + 2 * 3600 * 1000).toISOString(),
          channel: "WHATSAPP",
          status: "PENDING",
        },
      ],
      aiRecommendation: {
        action: "Send personalized WhatsApp 1-Click UPI Intent prompt (bypasses 3DS OTP friction).",
        actionType: "WHATSAPP_DUNNING",
        confidence: 0.89,
        reasoning: "Authentication drop-off on card. Switching channel to WhatsApp + UPI Autopay link yields 78% higher conversion for mid-market merchants.",
        optimalRetryTime: "Immediate",
        recommendedChannel: "WHATSAPP",
        expectedRecoveryProbability: 0.86,
      },
      customer: customers[1],
      payment: payments[1],
      subscription: subscriptions[1],
      timeline: [
        {
          id: "tl_010",
          timestamp: twoHoursAgo,
          title: "Card 3DS 2.0 Auth Dropped",
          description: "₹24,999 payment on ICICI Visa ended in PAYMENT_AUTHENTICATION_FAILED.",
          type: "PAYMENT_FAILED",
          actor: "RAZORPAY_WEBHOOK",
        },
        {
          id: "tl_011",
          timestamp: twoHoursAgo,
          title: "Alternative Payment Channel Dispatched",
          description: "WhatsApp interactive recovery message delivered with 1-click Razorpay checkout.",
          type: "ACTION_EXECUTED",
          actor: "RECOVER_AI_AGENT",
        },
      ],
      createdAt: twoHoursAgo,
      updatedAt: isoNow,
    },
    {
      id: "case_rec_003",
      caseNumber: "REC-2026-0893",
      customerId: "cust_chaicrafters_03",
      paymentId: "pay_chaicrafters_003",
      razorpayPaymentId: "pay_rzp_chai_7761",
      amount: 2499,
      currency: "INR",
      status: "OPEN",
      riskLevel: "MEDIUM",
      riskScore: 50,
      recoverabilityScore: 88,
      expectedRecoveryValue: 2199,
      priority: "P2",
      rootCause: "UPI_APP_TIMEOUT",
      rootCauseDetails: "UPI collect push expired after 300s without user unlocking PhonePe/GPay app.",
      selectedAction: "CREATE_PAYMENT_LINK",
      currentStep: "ROOT_CAUSE_ANALYSIS",
      actionsTakenCount: 1,
      recoveryAttempts: 1,
      recoveredAmount: 0,
      totalRecoveredAmount: 0,
      requiresHumanApproval: false,
      paymentLinkUrl: "https://rzp.io/i/demo_rec_chai_03",
      scheduledRetries: [],
      aiRecommendation: {
        action: "Trigger WhatsApp dynamic payment link with Razorpay QR Code & UPI deep-link.",
        actionType: "UPI_AUTOPAY_PROMPT",
        confidence: 0.91,
        reasoning: "D2C subscribers respond with highest conversion to instant WhatsApp notifications with clickable UPI deep links.",
        recommendedChannel: "WHATSAPP",
        expectedRecoveryProbability: 0.88,
      },
      customer: customers[2],
      payment: payments[2],
      timeline: [
        {
          id: "tl_020",
          timestamp: oneHourAgo,
          title: "UPI Collect Request Expired",
          description: "Collect request to rohit.sharma@okaxis timed out.",
          type: "PAYMENT_FAILED",
          actor: "RAZORPAY_WEBHOOK",
        },
      ],
      createdAt: oneHourAgo,
      updatedAt: isoNow,
    },
    {
      id: "case_rec_004",
      caseNumber: "REC-2026-0888",
      customerId: "cust_cloudnest_07",
      paymentId: "pay_cloudnest_007",
      razorpayPaymentId: "pay_rzp_cloud_9981",
      amount: 320000,
      currency: "INR",
      status: "RECOVERED",
      riskLevel: "CRITICAL",
      riskScore: 90,
      recoverabilityScore: 100,
      expectedRecoveryValue: 320000,
      priority: "P0",
      rootCause: "TEMPORARY_GATEWAY_GLITCH",
      rootCauseDetails: "Initial SBI mandate presentation timed out during peak interbank maintenance window.",
      selectedAction: "RETRY_SUBSCRIPTION",
      currentStep: "RECOVERY_RESOLVED",
      actionsTakenCount: 2,
      recoveryAttempts: 2,
      recoveredAmount: 320000,
      totalRecoveredAmount: 320000,
      requiresHumanApproval: true,
      scheduledRetries: [],
      aiRecommendation: {
        action: "Autonomous retry executed successfully at calculated optimal window.",
        actionType: "SMART_SCHEDULED_RETRY",
        confidence: 0.98,
        reasoning: "Transient gateway downtime resolved.",
        recommendedChannel: "AUTO_RETRY",
        expectedRecoveryProbability: 1.0,
      },
      customer: customers[5],
      payment: payments[4],
      timeline: [
        {
          id: "tl_030",
          timestamp: threeDaysAgo,
          title: "Mandate Failed on SBI Network",
          description: "₹3,20,000 annual charge failed due to GATEWAY_ERROR.",
          type: "PAYMENT_FAILED",
          actor: "RAZORPAY_WEBHOOK",
        },
        {
          id: "tl_031",
          timestamp: twoDaysAgo,
          title: "Payment Successfully Recovered",
          description: "Autonomous smart retry succeeded at 02:30 PM. ₹3,20,000 captured via Razorpay.",
          type: "PAYMENT_RECOVERED",
          actor: "RECOVER_AI_AGENT",
        },
      ],
      createdAt: threeDaysAgo,
      updatedAt: twoDaysAgo,
      recoveredAt: twoDaysAgo,
    },
  ];

  // 6. Revenue Risk Intelligence
  const revenueRisks: RevenueRisk[] = [
    {
      id: "risk_001",
      customerId: "cust_zenith_01",
      customerName: "Zenith Edutech Pvt Ltd",
      customerTier: "ENTERPRISE",
      riskScore: 78,
      churnProbability: 0.35,
      revenueAtRisk: 149999,
      riskTier: "CRITICAL",
      keyRiskFactors: [
        "First-time mandate failure on annual contract",
        "High contract value (₹1,49,999)",
        "End of month liquidity timing",
      ],
      recommendedAction: "Execute afternoon smart auto-retry + high-touch CSM fallback if unrecovered by Day 2",
      lastPaymentHealth: "DEGRADED",
      healthTrend: "STABLE",
      dunningSequenceName: "Enterprise Tier 1 Smart Dunning",
      consecutiveFailures: 1,
      lastFailureDate: fourHoursAgo,
      suggestedGracePeriodDays: 5,
      createdAt: fourHoursAgo,
    },
    {
      id: "risk_002",
      customerId: "cust_hyperlocal_02",
      customerName: "HyperLocal Logistics India",
      customerTier: "GROWTH",
      riskScore: 84,
      churnProbability: 0.42,
      revenueAtRisk: 24999,
      riskTier: "HIGH",
      keyRiskFactors: [
        "2 consecutive authentication drop-offs",
        "Decreasing login activity on merchant portal",
      ],
      recommendedAction: "Dispatch WhatsApp interactive Razorpay link with 1-click UPI Autopay migration",
      lastPaymentHealth: "CRITICAL",
      healthTrend: "DETERIORATING",
      dunningSequenceName: "Growth Interactive WhatsApp Flow",
      consecutiveFailures: 2,
      lastFailureDate: twoHoursAgo,
      suggestedGracePeriodDays: 3,
      createdAt: twoHoursAgo,
    },
    {
      id: "risk_003",
      customerId: "cust_logitrack_04",
      customerName: "LogiTrack Systems India",
      customerTier: "ENTERPRISE",
      riskScore: 72,
      churnProbability: 0.28,
      revenueAtRisk: 79000,
      riskTier: "HIGH",
      keyRiskFactors: [
        "Card expired (07/26)",
        "Mandate token needs re-consent with updated card details",
      ],
      recommendedAction: "Send branded Card Update Razorpay portal link with instant tokenization",
      lastPaymentHealth: "DEGRADED",
      healthTrend: "STABLE",
      dunningSequenceName: "Card Expiry Tokenization Dunning",
      consecutiveFailures: 1,
      lastFailureDate: oneDayAgo,
      suggestedGracePeriodDays: 7,
      createdAt: oneDayAgo,
    },
  ];

  // 7. Agent Decisions
  const agentDecisions: AgentDecision[] = [
    {
      id: "dec_001",
      caseId: "case_rec_001",
      caseNumber: "REC-2026-0891",
      customerId: "cust_zenith_01",
      customerName: "Zenith Edutech Pvt Ltd",
      amount: 149999,
      decisionType: "SCHEDULE_SMART_RETRY",
      confidence: 0.94,
      rationale: "Analysis of HDFC bank CBS clearing records indicates 89% higher debit success when presented during the 02:00 PM - 04:00 PM window versus 06:00 AM.",
      signalsDetected: [
        "Error: INSUFFICIENT_FUNDS during dawn clearing batch",
        "High LTV enterprise client (₹4.5L)",
        "Historical payment pattern: Active payroll on 1st of month",
      ],
      proposedAction: "Defer retry to 02:45 PM IST and prepare dynamic Razorpay UPI payment link",
      executedAction: "Scheduled Razorpay automated retry for 02:45 PM + WhatsApp briefing queued",
      channel: "RAZORPAY_RETRY",
      executionStatus: "EXECUTED",
      outcome: "Retry scheduled in system queue. Monitoring status.",
      humanReviewRequired: false,
      timestamp: fourHoursAgo,
    },
    {
      id: "dec_002",
      caseId: "case_rec_002",
      caseNumber: "REC-2026-0892",
      customerId: "cust_hyperlocal_02",
      customerName: "HyperLocal Logistics India",
      amount: 24999,
      decisionType: "SEND_WHATSAPP_INTERACTIVE_DUNNING",
      confidence: 0.89,
      rationale: "Card 3DS 2.0 auth dropped out. Dunning via email produces only 18% recovery for this cohort, while interactive WhatsApp with Razorpay pre-filled link produces 82%.",
      signalsDetected: [
        "Error: PAYMENT_AUTHENTICATION_FAILED",
        "Customer opened mobile app within past 30 mins",
        "Verified Indian business WhatsApp number",
      ],
      proposedAction: "Send WhatsApp template with personalized Razorpay payment link and one-touch UPI option",
      executedAction: "WhatsApp interactive message dispatched with dynamic link https://rzp.io/i/demo_rec_hyperlocal_02",
      channel: "WHATSAPP",
      executionStatus: "EXECUTED",
      outcome: "Message delivered with double tick; awaiting customer tap.",
      humanReviewRequired: false,
      timestamp: twoHoursAgo,
    },
    {
      id: "dec_003",
      caseId: "case_rec_004",
      caseNumber: "REC-2026-0888",
      customerId: "cust_cloudnest_07",
      customerName: "CloudNest Infrastructure Labs",
      amount: 320000,
      decisionType: "SCHEDULE_SMART_RETRY",
      confidence: 0.98,
      rationale: "SBI CBS downtime cleared. Heuristic model approved immediate retry.",
      signalsDetected: [
        "Error: GATEWAY_ERROR transient",
        "Downstream bank health restored to 99.4%",
      ],
      proposedAction: "Immediate mandate execution via Razorpay API",
      executedAction: "Triggered Razorpay charge API with payment ID pay_rzp_cloud_9981",
      channel: "RAZORPAY_RETRY",
      executionStatus: "COMPLETED",
      outcome: "Payment captured successfully! ₹3,20,000 recovered autonomously.",
      humanReviewRequired: false,
      timestamp: twoDaysAgo,
    },
  ];

  // 8. Audit Events
  const auditEvents: AuditEvent[] = [
    {
      id: "aud_001",
      entityType: "SANDBOX_SIMULATION",
      entityId: "system_init",
      eventType: "SANDBOX_ENVIRONMENT_BOOTSTRAPPED",
      actor: "SYSTEM",
      description: "VIREON Razorpay Demo Environment initialized with Indian merchant datasets.",
      payload: {
        mode: "sandbox",
        currency: "INR",
        merchant: "VIREON Technologies India",
      },
      timestamp: threeDaysAgo,
    },
    {
      id: "aud_002",
      entityType: "PAYMENT",
      entityId: "pay_zenith_001",
      eventType: "PAYMENT_FAILED_WEBHOOK_PROCESSED",
      actor: "RAZORPAY_WEBHOOK",
      description: "Received payment.failed event for ₹1,49,999 (Customer: Zenith Edutech Pvt Ltd).",
      payload: {
        paymentId: "pay_zenith_001",
        amount: 149999,
        errorCode: "INSUFFICIENT_FUNDS",
      },
      timestamp: fourHoursAgo,
    },
    {
      id: "aud_003",
      entityType: "AGENT_DECISION",
      entityId: "dec_001",
      eventType: "AGENT_DECISION_EXECUTED",
      actor: "RECOVER_AI_AGENT",
      description: "Agent decided: SCHEDULE_SMART_RETRY (Confidence 94%). Scheduled for 02:45 PM IST.",
      payload: {
        caseId: "case_rec_001",
        confidence: 0.94,
        targetWindow: "14:45 IST",
      },
      timestamp: fourHoursAgo,
    },
    {
      id: "aud_004",
      entityType: "RECOVERY_CASE",
      entityId: "case_rec_004",
      eventType: "REVENUE_RECOVERED_SUCCESS",
      actor: "RECOVER_AI_AGENT",
      description: "Autonomous recovery completed for CloudNest Infrastructure Labs (₹3,20,000 INR).",
      payload: {
        caseId: "case_rec_004",
        amountRecovered: 320000,
        method: "Razorpay Smart Retry",
      },
      timestamp: twoDaysAgo,
    },
  ];

  return {
    customers,
    payments,
    subscriptions,
    invoices,
    recoveryCases,
    revenueRisks,
    agentDecisions,
    auditEvents,
  };
}
